schema_version = "1.0.0"

id = "Three_d_Cursor_Snap"
version = "1.0.0"
name = "Three d Cursor Snap"
tagline = "Move 3d cursor like gizmo to snap vertex, edge and face"
maintainer = "Deepak"
type = "add-on"


tags = ["Object", "Modeling", "Mesh"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]